name: quay.tag
run-name: Creating new tag in quay based on pushed tag in Github.
on:
  push:
    tags:
      - '*'
jobs:
  copy-tag-to-quay:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install skopeo
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo
      - name: Login to quay.io
        shell: bash
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_BOT_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_BOT_PASSWORD }}
        run: |
         skopeo login quay.io -u ${QUAY_USERNAME} -p ${QUAY_TOKEN}
      - name: Get latest tag name
        id: tag
        run: echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
      - name: Get latest hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create new tag
        shell: bash
        env:
          TAG: ${{ steps.tag.outputs.tag }}
          HASH: ${{ steps.hash.outputs.hash }}
          IMAGE_REPO: ${{ secrets.QUAY_IMAGE_REPO }}
        run: |
          skopeo copy docker://${IMAGE_REPO}:main-${{ env.HASH }} docker://${IMAGE_REPO}:${{ env.TAG }}
